### ISSUE TITLE
[FEATURE] Allow for Thresholder to accept NaN values if the estimator allows for NaN values

### ISSUE THREAD

**Issue by vvandermeij** [koaning/scikit-lego#497]
It would be nice if the Thresholder does not do a 'check_X_y' when the estimator that it is used on allows for NaN values. A small example is shown below:

```
from sklego.meta import Thresholder
from sklearn.ensemble import HistGradientBoostingClassifier
import numpy as np

X = np.array([[np.nan, 4, 7, 3, 5], [5, 7, 2, 5, 7]])
y = np.array([1, 6, 8, 3, 2])

model = Thresholder(HistGradientBoostingClassifier(), threshold=0.7)
model.fit(X, y)
```

This piece of code gives a ValueError:

---------------------------------------------------------------------------
```
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_9212/2229818117.py in <module>
      6 
      7 model = Thresholder(HistGradientBoostingClassifier(), threshold=0.7)
----> 8 model.fit(X, y)

~\Anaconda3\envs\incasso\lib\site-packages\sklego\meta\thresholder.py in fit(self, X, y)
     50         :return: Returns an instance of self.
     51         """
---> 52         X, y = check_X_y(X, y, estimator=self, dtype=FLOAT_DTYPES)
     53         self.estimator_ = clone(self.model)
     54         if not isinstance(self.estimator_, ProbabilisticClassifier):

~\Anaconda3\envs\incasso\lib\site-packages\sklearn\utils\validation.py in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)
    954         raise ValueError("y cannot be None")
    955 
--> 956     X = check_array(
    957         X,
    958         accept_sparse=accept_sparse,

~\Anaconda3\envs\incasso\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    790 
    791         if force_all_finite:
--> 792             _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
    793 
    794     if ensure_min_samples > 0:

~\Anaconda3\envs\incasso\lib\site-packages\sklearn\utils\validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
    112         ):
    113             type_err = "infinity" if allow_nan else "NaN, infinity"
--> 114             raise ValueError(
    115                 msg_err.format(
    116                     type_err, msg_dtype if msg_dtype is not None else X.dtype

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by vvandermeij** [comment]
@MBrouns

**Comment by MBrouns** [comment]
@koaning I think we could just remove the `check_X` part for this meta estimator, assuming that the underlying estimator behaves nicely.

**Comment by koaning** [comment]
> I think we could just remove the check_X part for this meta estimator

Agreed. We may need to remove some of the tests for the component though. I think that's why it's added.

**Comment by koaning** [comment]
Mhm ... this example is an interesting one. It seems like the `HistGradientBoostingClassifier` still checks for shapes. When I remove the `check_X_y` from the Thresholder I now see this error in the unit test: 

```
ValueError: Found input variables with inconsistent numbers of samples: [2, 5]
```

**Comment by koaning** [comment]
For reproducibility. 

```python
import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier

X = np.array([[np.nan, 4, 7, 3, 5], [5, 7, 2, 5, 7]])
y = np.array([1, 6, 8, 3, 2])
model = HistGradientBoostingClassifier()
model.fit(X, y)
```

This returns this trace: 

```
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    model.fit(X, y)
  File "/home/vincent/Development/scikit-lego/venv/lib/python3.7/site-packages/sklearn/ensemble/_hist_gradient_boosting/gradient_boosting.py", line 233, in fit
    X, y = self._validate_data(X, y, dtype=[X_DTYPE], force_all_finite=False)
  File "/home/vincent/Development/scikit-lego/venv/lib/python3.7/site-packages/sklearn/base.py", line 576, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/vincent/Development/scikit-lego/venv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 973, in check_X_y
    check_consistent_length(X, y)
  File "/home/vincent/Development/scikit-lego/venv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 333, in check_consistent_length
    % [int(l) for l in lengths]
ValueError: Found input variables with inconsistent numbers of samples: [2, 5]
```

**Comment by MBrouns** [comment]
@koaning isn't that because the X array is defined the wrong way around (as a 2,5 matrix rather than a 5,2 matrix)?

**Comment by koaning** [comment]
d0h! Yeah you're right, this does run. 

```python
import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier

X = np.array([[np.nan, 4], [7, 3], [5, 5], [7, 2], [5, 7]])
y = np.array([1, 6, 8, 3, 2])
model = HistGradientBoostingClassifier()
model.fit(X, y)
```

The PR is in the works either way.
